# Global logging configuration
handlers = java.util.logging.ConsoleHandler, io.github.gabrielbbaldez.stacktale.jul.StacktaleJulHandler
.level = INFO

# ConsoleHandler configuration
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# StacktaleJulHandler configuration
io.github.gabrielbbaldez.stacktale.jul.StacktaleJulHandler.appPackages = com.example.demo
io.github.gabrielbbaldez.stacktale.jul.StacktaleJulHandler.file = target/errors-ai.log
